/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-03-23 02:21:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class ProductDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1740052119710L));
    _jspx_dependants.put("jar:file:/C:/Users/LEGION/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Chi Tiết Sản Phẩm</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --primary-color: #2e8b57;\r\n");
      out.write("            --primary-light: #3c9d74;\r\n");
      out.write("            --primary-dark: #236744;\r\n");
      out.write("            --accent-color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-family: 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Container styling */\r\n");
      out.write("        .product-container {\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            box-shadow: 0 6px 18px rgba(0, 0, 0, 0.08);\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Product image styling */\r\n");
      out.write("        .product-image-container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            height: 450px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            background-color: rgba(46, 139, 87, 0.05);\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-image {\r\n");
      out.write("            max-height: 400px;\r\n");
      out.write("            max-width: 100%;\r\n");
      out.write("            object-fit: contain;\r\n");
      out.write("            transition: transform 0.4s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-image-container:hover .product-image {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Product info styling */\r\n");
      out.write("        .product-title {\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 1.2rem;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding-bottom: 12px;\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-title::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: 3px;\r\n");
      out.write("            background-color: var(--primary-color);\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-description {\r\n");
      out.write("            color: #555;\r\n");
      out.write("            font-size: 1.05rem;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-price {\r\n");
      out.write("            color: var(--primary-light) !important;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            margin-top: 1.5rem;\r\n");
      out.write("            margin-bottom: 0.8rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stock-info {\r\n");
      out.write("            font-size: 0.95rem;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .stock-indicator {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 12px;\r\n");
      out.write("            height: 12px;\r\n");
      out.write("            background-color: #28a745;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            margin-right: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-divider {\r\n");
      out.write("            height: 1px;\r\n");
      out.write("            background-color: #eee;\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Size selection */\r\n");
      out.write("        .option-label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #444;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .size-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            gap: 12px;\r\n");
      out.write("            margin: 1rem 0 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .size-btn {\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            border: 2px solid #e0e0e0;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            transition: all 0.25s ease;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            min-width: 60px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .size-btn:hover {\r\n");
      out.write("            border-color: var(--primary-light);\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(46, 139, 87, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .size-btn.active {\r\n");
      out.write("            background-color: var(--primary-light);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-color: var(--primary-light);\r\n");
      out.write("            box-shadow: 0 5px 10px rgba(46, 139, 87, 0.25);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Quantity control */\r\n");
      out.write("        .quantity-controls {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin: 1.5rem 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .quantity-btn {\r\n");
      out.write("            border: 1px solid #e0e0e0;\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            width: 44px;\r\n");
      out.write("            height: 44px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .quantity-btn:hover {\r\n");
      out.write("            background-color: #e9ecef;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .quantity-input {\r\n");
      out.write("            width: 70px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            border: 1px solid #e0e0e0;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            height: 44px;\r\n");
      out.write("            margin: 0 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .quantity-label {\r\n");
      out.write("            margin-right: 15px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #444;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Action buttons */\r\n");
      out.write("        .action-buttons {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            margin-top: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-add-to-cart {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            border: 2px solid var(--primary-color);\r\n");
      out.write("            color: var(--primary-color);\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            padding: 14px 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-add-to-cart:hover {\r\n");
      out.write("            background-color: rgba(46, 139, 87, 0.1);\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(46, 139, 87, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-buy-now {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            background-color: var(--primary-color);\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            padding: 14px 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-buy-now:hover {\r\n");
      out.write("            background-color: var(--primary-dark);\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(46, 139, 87, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animation for page load */\r\n");
      out.write("        @keyframes fadeIn {\r\n");
      out.write("            from { opacity: 0; transform: translateY(20px); }\r\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .fade-in {\r\n");
      out.write("            animation: fadeIn 0.6s ease forwards;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .fade-in-delay-1 {\r\n");
      out.write("            animation: fadeIn 0.6s ease 0.2s forwards;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .fade-in-delay-2 {\r\n");
      out.write("            animation: fadeIn 0.6s ease 0.4s forwards;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive adjustments */\r\n");
      out.write("        @media (max-width: 991px) {\r\n");
      out.write("            .product-image-container {\r\n");
      out.write("                height: 400px;\r\n");
      out.write("                margin-bottom: 30px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .product-container {\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .product-image-container {\r\n");
      out.write("                height: 350px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .action-buttons {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 576px) {\r\n");
      out.write("            .product-title {\r\n");
      out.write("                font-size: 1.6rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .product-image-container {\r\n");
      out.write("                height: 300px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .size-container {\r\n");
      out.write("                justify-content: space-between;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .size-btn {\r\n");
      out.write("                padding: 10px 16px;\r\n");
      out.write("                min-width: 50px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container product-container fade-in\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <!-- Hình ảnh sản phẩm -->\r\n");
      out.write("        <div class=\"col-lg-5 mb-4 mb-lg-0\">\r\n");
      out.write("            <div class=\"product-image-container\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetails[0].imageURL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetails[0].productName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"product-image\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Thông tin sản phẩm -->\r\n");
      out.write("        <div class=\"col-lg-7 fade-in-delay-1\">\r\n");
      out.write("            <h1 class=\"product-title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetails[0].productName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("            <p class=\"product-description\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetails[0].description}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"product-divider\"></div>\r\n");
      out.write("\r\n");
      out.write("            <h2 class=\"product-price\"><span id=\"productPrice\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetails[0].price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> VND</h2>\r\n");
      out.write("            <div class=\"stock-info\">\r\n");
      out.write("                <span class=\"stock-indicator\"></span>\r\n");
      out.write("                <span id=\"stockCount\">Còn lại: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetails[0].stock}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" sản phẩm</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Form thêm vào giỏ hàng -->\r\n");
      out.write("            <form action=\"carts\" method=\"get\" class=\"fade-in-delay-2\">\r\n");
      out.write("                <input type=\"hidden\" id=\"productId\" name=\"productId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetails[0].productId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\" id=\"size\" name=\"size\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("                <!-- Chọn kích thước -->\r\n");
      out.write("                <div class=\"mb-4\">\r\n");
      out.write("                    <label class=\"option-label\">Chọn kích thước:</label>\r\n");
      out.write("                    <div class=\"size-container\" id=\"sizeOptions\">\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Chọn số lượng -->\r\n");
      out.write("                <div class=\"mb-4\">\r\n");
      out.write("                    <label class=\"option-label\">Số lượng:</label>\r\n");
      out.write("                    <div class=\"quantity-controls\">\r\n");
      out.write("                        <button type=\"button\" id=\"decreaseQty\" class=\"quantity-btn\">-</button>\r\n");
      out.write("                        <input type=\"number\" id=\"quantity\" name=\"quantity\" value=\"1\" min=\"1\"\r\n");
      out.write("                               max=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productDetails[0].stock}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"quantity-input\">\r\n");
      out.write("                        <button type=\"button\" id=\"increaseQty\" class=\"quantity-btn\">+</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Nút thêm vào giỏ -->\r\n");
      out.write("                <div class=\"action-buttons\">\r\n");
      out.write("                    <button type=\"button\" id=\"addToCartBtn\" class=\"btn-add-to-cart\">\r\n");
      out.write("                        <i class=\"fas fa-shopping-cart\"></i>\r\n");
      out.write("                        THÊM VÀO GIỎ\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <button type=\"submit\" name=\"action\" value=\"buyNow\" class=\"btn-buy-now\">\r\n");
      out.write("                        <i class=\"fas fa-bolt\"></i>\r\n");
      out.write("                        MUA NGAY\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("        let selectedSize = \"\";\r\n");
      out.write("\r\n");
      out.write("        // Chọn kích thước và cập nhật giá + số lượng\r\n");
      out.write("        $(\".size-btn\").click(function () {\r\n");
      out.write("            $(\".size-btn\").removeClass(\"active\");\r\n");
      out.write("            $(this).addClass(\"active\");\r\n");
      out.write("\r\n");
      out.write("            let price = $(this).data(\"price\");\r\n");
      out.write("            let stock = $(this).data(\"stock\");\r\n");
      out.write("            selectedSize = $(this).data(\"size\");\r\n");
      out.write("\r\n");
      out.write("            $(\"#productPrice\").text(price);\r\n");
      out.write("            $(\"#stockCount\").text(\"Còn lại: \" + stock + \" sản phẩm\");\r\n");
      out.write("            $(\"#quantity\").attr(\"max\", stock);\r\n");
      out.write("            $(\"#size\").val(selectedSize);\r\n");
      out.write("\r\n");
      out.write("            // Reset quantity to 1 when changing size\r\n");
      out.write("            $(\"#quantity\").val(1);\r\n");
      out.write("\r\n");
      out.write("            // Update stock indicator color\r\n");
      out.write("            if (stock > 10) {\r\n");
      out.write("                $(\".stock-indicator\").css(\"background-color\", \"#28a745\"); // Green\r\n");
      out.write("            } else if (stock > 5) {\r\n");
      out.write("                $(\".stock-indicator\").css(\"background-color\", \"#ffc107\"); // Yellow\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\".stock-indicator\").css(\"background-color\", \"#dc3545\"); // Red\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Nút tăng giảm số lượng\r\n");
      out.write("        $(\"#increaseQty\").click(function () {\r\n");
      out.write("            let maxQty = parseInt($(\"#quantity\").attr(\"max\"));\r\n");
      out.write("            let currentQty = parseInt($(\"#quantity\").val());\r\n");
      out.write("            if (currentQty < maxQty) $(\"#quantity\").val(currentQty + 1);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(\"#decreaseQty\").click(function () {\r\n");
      out.write("            let currentQty = parseInt($(\"#quantity\").val());\r\n");
      out.write("            if (currentQty > 1) $(\"#quantity\").val(currentQty - 1);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Validate quantity input\r\n");
      out.write("        $(\"#quantity\").on('input', function() {\r\n");
      out.write("            let maxQty = parseInt($(this).attr(\"max\"));\r\n");
      out.write("            let currentQty = parseInt($(this).val());\r\n");
      out.write("\r\n");
      out.write("            if (isNaN(currentQty) || currentQty < 1) {\r\n");
      out.write("                $(this).val(1);\r\n");
      out.write("            } else if (currentQty > maxQty) {\r\n");
      out.write("                $(this).val(maxQty);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Kiểm tra trước khi submit form\r\n");
      out.write("        $(\"#addToCartBtn\").click(function (event) {\r\n");
      out.write("            event.preventDefault();\r\n");
      out.write("\r\n");
      out.write("            if ($(\"#size\").val() === \"\") {\r\n");
      out.write("                alert(\"Vui lòng chọn kích thước!\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            let productId = $(\"#productId\").val();\r\n");
      out.write("            let size = $(\"#size\").val();\r\n");
      out.write("            let quantity = $(\"#quantity\").val();\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                url: \"carts\",\r\n");
      out.write("                data: {\r\n");
      out.write("                    action: \"addToCart\",\r\n");
      out.write("                    productId: productId,\r\n");
      out.write("                    size: size,\r\n");
      out.write("                    quantity: quantity\r\n");
      out.write("                },\r\n");
      out.write("                success: function (response) {\r\n");
      out.write("                    let newCartCount = response.cartCount || 0;\r\n");
      out.write("                    $(\"#cartCount\").text(newCartCount);\r\n");
      out.write("\r\n");
      out.write("                    // Show success toast instead of alert\r\n");
      out.write("                    const successToast = `\r\n");
      out.write("                        <div class=\"position-fixed bottom-0 end-0 p-3\" style=\"z-index: 11\">\r\n");
      out.write("                            <div class=\"toast show\" role=\"alert\" aria-live=\"assertive\" aria-atomic=\"true\">\r\n");
      out.write("                                <div class=\"toast-header bg-success text-white\">\r\n");
      out.write("                                    <strong class=\"me-auto\"><i class=\"fas fa-check-circle\"></i> Thành công</strong>\r\n");
      out.write("                                    <button type=\"button\" class=\"btn-close btn-close-white\" data-bs-dismiss=\"toast\"></button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"toast-body\">\r\n");
      out.write("                                    Đã thêm sản phẩm vào giỏ hàng thành công!\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    `;\r\n");
      out.write("\r\n");
      out.write("                    $('body').append(successToast);\r\n");
      out.write("                    setTimeout(() => {\r\n");
      out.write("                        $('.toast').toast('hide');\r\n");
      out.write("                        setTimeout(() => {\r\n");
      out.write("                            $('.toast').parent().remove();\r\n");
      out.write("                        }, 500);\r\n");
      out.write("                    }, 3000);\r\n");
      out.write("                },\r\n");
      out.write("                error: function () {\r\n");
      out.write("                    alert(\"Có lỗi xảy ra, vui lòng thử lại\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Highlight the first size by default\r\n");
      out.write("        if ($(\".size-btn\").length > 0) {\r\n");
      out.write("            $(\".size-btn:first\").click();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /product/ProductDetail.jsp(352,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("entry");
    // /product/ProductDetail.jsp(352,24) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/product/ProductDetail.jsp(352,24) '${productDetails}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${productDetails}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            <button type=\"button\" class=\"size-btn\" data-size=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" data-price=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("                                    data-stock=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.stock}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" data-productid=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.productId}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                    ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                            </button>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }
}
