/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-03-23 02:21:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.cart;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1740052119710L));
    _jspx_dependants.put("jar:file:/C:/Users/LEGION/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Giỏ Hàng</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        /* General body styling */\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-family: 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Cart container styling */\r\n");
      out.write("        .cart-container {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 40px auto;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.08);\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            animation: slideIn 0.5s ease forwards;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Headings */\r\n");
      out.write("        .cart-header {\r\n");
      out.write("            color: #2e8b57;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            padding-bottom: 15px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 2.2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-header::after {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            transform: translateX(-50%);\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 4px;\r\n");
      out.write("            background: linear-gradient(90deg, #2e8b57, #5BBD8C);\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .section-title {\r\n");
      out.write("            color: #2e8b57;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin: 1.5rem 0 1rem;\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Cart items */\r\n");
      out.write("        .cart-items-wrapper {\r\n");
      out.write("            margin: 30px 0;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.03);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            border-bottom: 1px solid #e0e0e0;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-item:last-child {\r\n");
      out.write("            border-bottom: none;\r\n");
      out.write("            margin-bottom: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-item:hover {\r\n");
      out.write("            background-color: #f9fafb;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(0, 0, 0, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-info {\r\n");
      out.write("            flex: 2;\r\n");
      out.write("            padding-left: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-name {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .product-variant {\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            margin-top: 4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Quantity controls */\r\n");
      out.write("        .quantity-control {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .quantity-btn {\r\n");
      out.write("            width: 36px;\r\n");
      out.write("            height: 36px;\r\n");
      out.write("            background-color: #f1f8f3;\r\n");
      out.write("            border: 1px solid #cbe3d7;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #2e8b57;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .quantity-btn:hover {\r\n");
      out.write("            background-color: #2e8b57;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-color: #2e8b57;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .quantity-input {\r\n");
      out.write("            width: 60px;\r\n");
      out.write("            height: 36px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border: 1px solid #cbe3d7;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #2e8b57;\r\n");
      out.write("            margin: 0 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Price and subtotal */\r\n");
      out.write("        .price-info {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            padding-right: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .price {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #2e8b57;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            margin-bottom: 4px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .subtotal {\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            color: #666;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Remove button */\r\n");
      out.write("        .remove-btn {\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            color: #dc3545;\r\n");
      out.write("            border: 1px solid #f8d7da;\r\n");
      out.write("            padding: 8px 15px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .remove-btn:hover {\r\n");
      out.write("            background-color: #dc3545;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-color: #dc3545;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Total price */\r\n");
      out.write("        .total-price-container {\r\n");
      out.write("            padding: 20px 25px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            background: linear-gradient(145deg, #f1f8f3, #e7f4eb);\r\n");
      out.write("            margin: 2rem 0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(46, 139, 87, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .total-price-label {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .total-price-value {\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #2e8b57;\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Checkout button */\r\n");
      out.write("        .btn-checkout {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin: 2rem auto;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            background: linear-gradient(135deg, #3c9d74, #2e8b57);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(46, 139, 87, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-checkout:hover {\r\n");
      out.write("            background: linear-gradient(135deg, #2e8b57, #267349);\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(46, 139, 87, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-checkout:disabled {\r\n");
      out.write("            background: linear-gradient(135deg, #a6a6a6, #858585);\r\n");
      out.write("            color: #eeeeee;\r\n");
      out.write("            cursor: not-allowed;\r\n");
      out.write("            transform: none;\r\n");
      out.write("            box-shadow: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Select all container */\r\n");
      out.write("        .select-all-container {\r\n");
      out.write("            margin: 15px 0;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            background-color: #f1f8f3;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.03);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .select-all-container input {\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("            accent-color: #2e8b57;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .select-all-container label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #2e8b57;\r\n");
      out.write("            margin-bottom: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Payment options */\r\n");
      out.write("        .payment-options {\r\n");
      out.write("            margin: 1.5rem 0;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            background-color: #f1f8f3;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.03);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-method-title {\r\n");
      out.write("            color: #2e8b57;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-method {\r\n");
      out.write("            margin: 15px 0;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.03);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-method:hover {\r\n");
      out.write("            box-shadow: 0 5px 10px rgba(0, 0, 0, 0.07);\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-method-radio {\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("            accent-color: #2e8b57;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-method-label {\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            color: #444;\r\n");
      out.write("            margin-bottom: 0;\r\n");
      out.write("            flex: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .payment-icon {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            color: #2e8b57;\r\n");
      out.write("            margin-right: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Back to store button */\r\n");
      out.write("        .btn-back {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: all 0.2s ease;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            border: 2px solid #e0e0e0;\r\n");
      out.write("            color: #444;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-back:hover {\r\n");
      out.write("            background-color: #f1f8f3;\r\n");
      out.write("            border-color: #2e8b57;\r\n");
      out.write("            color: #2e8b57;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Empty cart message */\r\n");
      out.write("        .empty-cart {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 50px 20px;\r\n");
      out.write("            background-color: #f9fafb;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            margin: 30px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .empty-cart-icon {\r\n");
      out.write("            font-size: 4rem;\r\n");
      out.write("            color: #a6a6a6;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .empty-cart-message {\r\n");
      out.write("            font-size: 1.4rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-shop-now {\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("            padding: 12px 25px;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            background: linear-gradient(135deg, #3c9d74, #2e8b57);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(46, 139, 87, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-shop-now:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(46, 139, 87, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Checkbox styling */\r\n");
      out.write("        .select-item {\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("            accent-color: #2e8b57;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animations */\r\n");
      out.write("        @keyframes slideIn {\r\n");
      out.write("            from { opacity: 0; transform: translateY(30px); }\r\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeIn {\r\n");
      out.write("            from { opacity: 0; }\r\n");
      out.write("            to { opacity: 1; }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Individual item animation */\r\n");
      out.write("        .cart-item {\r\n");
      out.write("            animation: fadeIn 0.5s ease forwards;\r\n");
      out.write("            animation-delay: calc(var(--animation-order) * 0.1s);\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Adding animation delay for each item */\r\n");
      out.write("        #cart-items-container > div:nth-child(1) { --animation-order: 1; }\r\n");
      out.write("        #cart-items-container > div:nth-child(2) { --animation-order: 2; }\r\n");
      out.write("        #cart-items-container > div:nth-child(3) { --animation-order: 3; }\r\n");
      out.write("        #cart-items-container > div:nth-child(4) { --animation-order: 4; }\r\n");
      out.write("        #cart-items-container > div:nth-child(5) { --animation-order: 5; }\r\n");
      out.write("        #cart-items-container > div:nth-child(6) { --animation-order: 6; }\r\n");
      out.write("        #cart-items-container > div:nth-child(7) { --animation-order: 7; }\r\n");
      out.write("        #cart-items-container > div:nth-child(8) { --animation-order: 8; }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive adjustments */\r\n");
      out.write("        @media (max-width: 992px) {\r\n");
      out.write("            .cart-container {\r\n");
      out.write("                width: 95%;\r\n");
      out.write("                padding: 20px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .cart-item {\r\n");
      out.write("                flex-wrap: wrap;\r\n");
      out.write("                padding: 15px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .product-info {\r\n");
      out.write("                flex: 100%;\r\n");
      out.write("                order: 1;\r\n");
      out.write("                padding-left: 0;\r\n");
      out.write("                margin-bottom: 15px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .quantity-control {\r\n");
      out.write("                flex: 1;\r\n");
      out.write("                order: 2;\r\n");
      out.write("                justify-content: flex-start;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .price-info {\r\n");
      out.write("                flex: 1;\r\n");
      out.write("                order: 3;\r\n");
      out.write("                text-align: right;\r\n");
      out.write("                padding-right: 0;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .action-buttons {\r\n");
      out.write("                flex: 100%;\r\n");
      out.write("                order: 4;\r\n");
      out.write("                margin-top: 15px;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                justify-content: flex-end;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 576px) {\r\n");
      out.write("            .cart-header {\r\n");
      out.write("                font-size: 1.8rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .total-price-value {\r\n");
      out.write("                font-size: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .btn-checkout {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"cart-container\">\r\n");
      out.write("    <h2 class=\"cart-header\"><i class=\"fas fa-shopping-cart\"></i> Giỏ Hàng Của Bạn</h2>\r\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?action=find\" class=\"btn btn-back\">\r\n");
      out.write("        <i class=\"fas fa-arrow-left\"></i> Quay lại cửa hàng\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    let timeoutMap = {}; // Store timeout for each product to prevent multiple AJAX calls\r\n");
      out.write("\r\n");
      out.write("    // Function to change quantity of a product\r\n");
      out.write("    function changeQuantity(amount, productVariantId, price) {\r\n");
      out.write("        let quantityInput = document.getElementById(\"quantity-\" + productVariantId);\r\n");
      out.write("\r\n");
      out.write("        let currentQuantity = parseInt(quantityInput.value) || 1;\r\n");
      out.write("        let newQuantity = Math.max(1, currentQuantity + amount); // Ensure quantity doesn't go below 1\r\n");
      out.write("        quantityInput.value = newQuantity;\r\n");
      out.write("\r\n");
      out.write("        if (timeoutMap[productVariantId]) clearTimeout(timeoutMap[productVariantId]);\r\n");
      out.write("\r\n");
      out.write("        timeoutMap[productVariantId] = setTimeout(function () {\r\n");
      out.write("            // Send AJAX request to update the cart\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/carts\",\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                data: {\r\n");
      out.write("                    action: \"update\",\r\n");
      out.write("                    quantity: newQuantity,\r\n");
      out.write("                    productVariantId: productVariantId\r\n");
      out.write("                },\r\n");
      out.write("                success: function (response) {\r\n");
      out.write("                    // Update the quantity data attribute\r\n");
      out.write("                    $(\".select-item[data-id='\" + productVariantId + \"']\").data('quantity', newQuantity);\r\n");
      out.write("\r\n");
      out.write("                    // Update the subtotal\r\n");
      out.write("                    let subtotal = newQuantity * price;\r\n");
      out.write("                    $(\"#subtotal-\" + productVariantId).text(\"Tổng: \" + subtotal + \" VND\");\r\n");
      out.write("\r\n");
      out.write("                    let newCartCount = response.cartCount || 0;\r\n");
      out.write("                    $(\"#cartCount\").text(newCartCount);\r\n");
      out.write("\r\n");
      out.write("                    // Recalculate total price\r\n");
      out.write("                    updateTotalPrice();\r\n");
      out.write("                },\r\n");
      out.write("                error: function () {\r\n");
      out.write("                    alert(\"Lỗi không thể cập nhật giỏ hàng!\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }, 500); // Delay AJAX request by 500ms to prevent rapid calls\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function validateQuantity(productVariantId, price) {\r\n");
      out.write("        let quantityInput = document.getElementById(\"quantity-\" + productVariantId);\r\n");
      out.write("        let newQuantity = parseInt(quantityInput.value) || 1;\r\n");
      out.write("\r\n");
      out.write("        // Ensure the quantity is at least 1\r\n");
      out.write("        if (newQuantity < 1) {\r\n");
      out.write("            quantityInput.value = 1;\r\n");
      out.write("            newQuantity = 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (timeoutMap[productVariantId]) clearTimeout(timeoutMap[productVariantId]);\r\n");
      out.write("\r\n");
      out.write("        timeoutMap[productVariantId] = setTimeout(function () {\r\n");
      out.write("            // Send AJAX request to update the cart\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/carts\",\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                data: {\r\n");
      out.write("                    action: \"update\",\r\n");
      out.write("                    quantity: newQuantity,\r\n");
      out.write("                    productVariantId: productVariantId\r\n");
      out.write("                },\r\n");
      out.write("                success: function (response) {\r\n");
      out.write("                    // Update the quantity data attribute\r\n");
      out.write("                    $(\".select-item[data-id='\" + productVariantId + \"']\").data('quantity', newQuantity);\r\n");
      out.write("\r\n");
      out.write("                    // Update the subtotal\r\n");
      out.write("                    let subtotal = newQuantity * price;\r\n");
      out.write("                    $(\"#subtotal-\" + productVariantId).text(\"Tổng: \" + subtotal + \" VND\");\r\n");
      out.write("\r\n");
      out.write("                    let newCartCount = response.cartCount || 0;\r\n");
      out.write("                    $(\"#cartCount\").text(newCartCount);\r\n");
      out.write("\r\n");
      out.write("                    // Recalculate total price\r\n");
      out.write("                    updateTotalPrice();\r\n");
      out.write("                },\r\n");
      out.write("                error: function () {\r\n");
      out.write("                    alert(\"Lỗi không thể cập nhật giỏ hàng!\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }, 500); // Delay AJAX request by 500ms to prevent rapid calls\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Function to calculate and update the total price of selected items\r\n");
      out.write("    function updateTotalPrice() {\r\n");
      out.write("        let total = 0;\r\n");
      out.write("        let selectedCount = 0;\r\n");
      out.write("\r\n");
      out.write("        // Loop through each selected cart item and add its subtotal to the total\r\n");
      out.write("        $('.select-item:checked').each(function () {\r\n");
      out.write("            let price = parseInt($(this).data('price'));\r\n");
      out.write("            let quantity = parseInt($(this).data('quantity'));\r\n");
      out.write("            total += price * quantity;\r\n");
      out.write("            selectedCount++;\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Format total with thousand separators\r\n");
      out.write("        let formattedTotal = total.toLocaleString('vi-VN');\r\n");
      out.write("\r\n");
      out.write("        // Update the displayed total price\r\n");
      out.write("        $('.total-price-value').text(formattedTotal + ' VND');\r\n");
      out.write("\r\n");
      out.write("        // Enable/disable checkout button based on selections\r\n");
      out.write("        if (selectedCount > 0) {\r\n");
      out.write("            $('#checkout-button').prop('disabled', false);\r\n");
      out.write("        } else {\r\n");
      out.write("            $('#checkout-button').prop('disabled', true);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Update select all checkbox\r\n");
      out.write("        updateSelectAllCheckbox();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function prepareCheckout() {\r\n");
      out.write("        let selectedItems = [];\r\n");
      out.write("        $('.select-item:checked').each(function() {\r\n");
      out.write("            selectedItems.push($(this).data('id'));\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        if (selectedItems.length === 0) {\r\n");
      out.write("            alert(\"Vui lòng chọn ít nhất một sản phẩm để thanh toán.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        let paymentMethod = $('input[name=\"paymentMethod\"]:checked').val();\r\n");
      out.write("\r\n");
      out.write("        // Prepare the data to send\r\n");
      out.write("        let data = {\r\n");
      out.write("            selectedItems: selectedItems,\r\n");
      out.write("            paymentMethod: paymentMethod\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        // Send the AJAX request\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/checkout\",\r\n");
      out.write("            type: \"POST\",\r\n");
      out.write("            contentType: \"application/json\",\r\n");
      out.write("            data: JSON.stringify(data),\r\n");
      out.write("            beforeSend: function() {\r\n");
      out.write("                // Disable button and show loading state\r\n");
      out.write("                $('#checkout-button').prop('disabled', true);\r\n");
      out.write("                $('#checkout-button').html('<i class=\"fas fa-spinner fa-spin\"></i> Đang xử lý...');\r\n");
      out.write("            },\r\n");
      out.write("            success: function(response) {\r\n");
      out.write("                if (response.error) {\r\n");
      out.write("                    alert(response.error);\r\n");
      out.write("                    // Reset button state\r\n");
      out.write("                    $('#checkout-button').prop('disabled', false);\r\n");
      out.write("                    $('#checkout-button').html('<i class=\"fas fa-check-circle\"></i> Tiến hành thanh toán');\r\n");
      out.write("                } else if (response.paymentUrl) {\r\n");
      out.write("                    window.location.href = response.paymentUrl;\r\n");
      out.write("                } else {\r\n");
      out.write("                    window.location.href = response.redirectURL + \"?orderId=\" + response.orderId + \"&totalPrice=\" + response.totalPrice;\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error: function(xhr, status, error) {\r\n");
      out.write("                alert(\"Lỗi khi xử lý thanh toán: \" + error);\r\n");
      out.write("                // Reset button state\r\n");
      out.write("                $('#checkout-button').prop('disabled', false);\r\n");
      out.write("                $('#checkout-button').html('<i class=\"fas fa-check-circle\"></i> Tiến hành thanh toán');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        return false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function deleteCartItem(productVariantId) {\r\n");
      out.write("        // Show confirmation dialog\r\n");
      out.write("        if (!confirm(\"Bạn có chắc chắn muốn xóa sản phẩm này khỏi giỏ hàng?\")) {\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/carts\",\r\n");
      out.write("            type: \"POST\",\r\n");
      out.write("            data: {\r\n");
      out.write("                action: \"delete\",\r\n");
      out.write("                productVariantId: productVariantId\r\n");
      out.write("            },\r\n");
      out.write("            beforeSend: function() {\r\n");
      out.write("                // Add visual feedback for delete operation\r\n");
      out.write("                $(\"#item-\" + productVariantId).css('opacity', '0.5');\r\n");
      out.write("            },\r\n");
      out.write("            success: function(response) {\r\n");
      out.write("                // Remove item with animation\r\n");
      out.write("                $(\"#item-\" + productVariantId).slideUp(300, function() {\r\n");
      out.write("                    $(this).remove();\r\n");
      out.write("\r\n");
      out.write("                    // Update cart count\r\n");
      out.write("                    let newCartCount = response.cartCount || 0;\r\n");
      out.write("                    $(\"#cartCount\").text(newCartCount);\r\n");
      out.write("\r\n");
      out.write("                    // Recalculate total price\r\n");
      out.write("                    updateTotalPrice();\r\n");
      out.write("\r\n");
      out.write("                    // Check if cart is empty\r\n");
      out.write("                    if ($('.cart-item').length === 0) {\r\n");
      out.write("                        $('.cart-container').html(`\r\n");
      out.write("                            <h2 class=\"cart-header\"><i class=\"fas fa-shopping-cart\"></i> Giỏ Hàng Của Bạn</h2>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?action=find\" class=\"btn btn-back\">\r\n");
      out.write("                                <i class=\"fas fa-arrow-left\"></i> Quay lại cửa hàng\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"empty-cart\">\r\n");
      out.write("                                <div class=\"empty-cart-icon\">\r\n");
      out.write("                                    <i class=\"fas fa-shopping-cart\"></i>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"empty-cart-message\">Giỏ hàng của bạn đang trống</div>\r\n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?action=find\" class=\"btn-shop-now\">\r\n");
      out.write("                                    <i class=\"fas fa-store\"></i> Bắt đầu mua sắm\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        `);\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            },\r\n");
      out.write("            error: function() {\r\n");
      out.write("                alert(\"Lỗi không thể xóa sản phẩm!\");\r\n");
      out.write("                // Restore opacity if delete fails\r\n");
      out.write("                $(\"#item-\" + productVariantId).css('opacity', '1');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Toggle all items selection\r\n");
      out.write("    function toggleSelectAll() {\r\n");
      out.write("        let isChecked = $('#select-all').prop('checked');\r\n");
      out.write("        $('.select-item').prop('checked', isChecked);\r\n");
      out.write("        updateTotalPrice();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Update select all checkbox state based on individual selections\r\n");
      out.write("    function updateSelectAllCheckbox() {\r\n");
      out.write("        let totalItems = $('.select-item').length;\r\n");
      out.write("        let selectedItems = $('.select-item:checked').length;\r\n");
      out.write("\r\n");
      out.write("        if (selectedItems === 0) {\r\n");
      out.write("            $('#select-all').prop('checked', false);\r\n");
      out.write("            $('#select-all').prop('indeterminate', false);\r\n");
      out.write("        } else if (selectedItems === totalItems) {\r\n");
      out.write("            $('#select-all').prop('checked', true);\r\n");
      out.write("            $('#select-all').prop('indeterminate', false);\r\n");
      out.write("        } else {\r\n");
      out.write("            $('#select-all').prop('indeterminate', true);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("        // Initialize total price on page load\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("            updateTotalPrice();\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /cart/Cart.jsp(493,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("cart");
    // /cart/Cart.jsp(493,4) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/cart/Cart.jsp(493,4) '${sessionScope.cart}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.cart}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("        ");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("        ");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("    ");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /cart/Cart.jsp(495,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty cart.items}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            <div class=\"empty-cart\">\r\n");
        out.write("                <div class=\"empty-cart-icon\">\r\n");
        out.write("                    <i class=\"fas fa-shopping-cart\"></i>\r\n");
        out.write("                </div>\r\n");
        out.write("                <div class=\"empty-cart-message\">Giỏ hàng của bạn đang trống</div>\r\n");
        out.write("                <a href=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/products?action=find\" class=\"btn-shop-now\">\r\n");
        out.write("                    <i class=\"fas fa-store\"></i> Bắt đầu mua sắm\r\n");
        out.write("                </a>\r\n");
        out.write("            </div>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            <div class=\"select-all-container\">\r\n");
        out.write("                <input type=\"checkbox\" id=\"select-all\" onchange=\"toggleSelectAll()\">\r\n");
        out.write("                <label for=\"select-all\">Chọn tất cả sản phẩm</label>\r\n");
        out.write("            </div>\r\n");
        out.write("\r\n");
        out.write("            <div class=\"cart-items-wrapper\">\r\n");
        out.write("                <div id=\"cart-items-container\">\r\n");
        out.write("                    ");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                </div>\r\n");
        out.write("            </div>\r\n");
        out.write("\r\n");
        out.write("            <div class=\"total-price-container\">\r\n");
        out.write("                <div class=\"total-price-label\">Tổng tiền:</div>\r\n");
        out.write("                <div class=\"total-price-value\">0 VND</div>\r\n");
        out.write("            </div>\r\n");
        out.write("\r\n");
        out.write("            <form action=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("/checkout\" method=\"post\" onsubmit=\"return prepareCheckout()\">\r\n");
        out.write("                <input type=\"hidden\" name=\"selectedItems\" id=\"selectedItems\" value=\"\">\r\n");
        out.write("\r\n");
        out.write("                <div class=\"payment-options\">\r\n");
        out.write("                    <div class=\"payment-method-title\">Phương thức thanh toán</div>\r\n");
        out.write("\r\n");
        out.write("                    <div class=\"payment-method\">\r\n");
        out.write("                        <input class=\"payment-method-radio\" type=\"radio\" name=\"paymentMethod\" id=\"cod\" value=\"cod\" checked>\r\n");
        out.write("                        <label class=\"payment-method-label\" for=\"cod\">\r\n");
        out.write("                            <i class=\"fas fa-money-bill-wave payment-icon\"></i> Thanh toán khi nhận hàng (COD)\r\n");
        out.write("                        </label>\r\n");
        out.write("                    </div>\r\n");
        out.write("\r\n");
        out.write("                    <div class=\"payment-method\">\r\n");
        out.write("                        <input class=\"payment-method-radio\" type=\"radio\" name=\"paymentMethod\" id=\"vnpay\" value=\"vnpay\">\r\n");
        out.write("                        <label class=\"payment-method-label\" for=\"vnpay\">\r\n");
        out.write("                            <i class=\"fas fa-credit-card payment-icon\"></i> Thanh toán qua VNPay\r\n");
        out.write("                        </label>\r\n");
        out.write("                    </div>\r\n");
        out.write("                </div>\r\n");
        out.write("\r\n");
        out.write("                <button type=\"submit\" class=\"btn-checkout\" id=\"checkout-button\" disabled>\r\n");
        out.write("                    <i class=\"fas fa-check-circle\"></i> Tiến hành thanh toán\r\n");
        out.write("                </button>\r\n");
        out.write("            </form>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
    // /cart/Cart.jsp(514,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("entry");
    // /cart/Cart.jsp(514,20) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/cart/Cart.jsp(514,20) '${cart.items}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cart.items}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_c_005fset_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("                        ");
          if (_jspx_meth_c_005fset_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("                        <div class=\"cart-item\" id=\"item-");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                            <input type=\"checkbox\" class=\"select-item\" data-id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" data-price=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" data-quantity=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartItem.quantity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" onchange=\"updateTotalPrice()\">\r\n");
          out.write("\r\n");
          out.write("                            <div class=\"product-info\">\r\n");
          out.write("                                <div class=\"product-name\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("                                <div class=\"product-variant\">Kích cỡ: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("                            </div>\r\n");
          out.write("\r\n");
          out.write("                            <div class=\"quantity-control\">\r\n");
          out.write("                                <button type=\"button\"\r\n");
          out.write("                                        onclick=\"changeQuantity(-1, ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(',');
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\"\r\n");
          out.write("                                        class=\"quantity-btn\">\r\n");
          out.write("                                    <i class=\"fas fa-minus\"></i>\r\n");
          out.write("                                </button>\r\n");
          out.write("                                <input type=\"number\" id=\"quantity-");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"quantity-input\"\r\n");
          out.write("                                       name=\"quantity\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartItem.quantity}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" min=\"1\"\r\n");
          out.write("                                       oninput=\"validateQuantity(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(',');
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\">\r\n");
          out.write("                                <button type=\"button\"\r\n");
          out.write("                                        onclick=\"changeQuantity(1, ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(',');
          out.write(' ');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\"\r\n");
          out.write("                                        class=\"quantity-btn\">\r\n");
          out.write("                                    <i class=\"fas fa-plus\"></i>\r\n");
          out.write("                                </button>\r\n");
          out.write("                            </div>\r\n");
          out.write("\r\n");
          out.write("                            <div class=\"price-info\">\r\n");
          out.write("                                <div class=\"price\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" VND</div>\r\n");
          out.write("                                <div class=\"subtotal\" id=\"subtotal-");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                    Tổng: ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartItem.quantity * productVariant.price}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" VND\r\n");
          out.write("                                </div>\r\n");
          out.write("                            </div>\r\n");
          out.write("\r\n");
          out.write("                            <div class=\"action-buttons\">\r\n");
          out.write("                                <button type=\"button\" onclick=\"deleteCartItem(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productVariant.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\" class=\"remove-btn\">\r\n");
          out.write("                                    <i class=\"fas fa-trash-alt\"></i> Xóa\r\n");
          out.write("                                </button>\r\n");
          out.write("                            </div>\r\n");
          out.write("                        </div>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /cart/Cart.jsp(515,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("cartItem");
    // /cart/Cart.jsp(515,24) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/cart/Cart.jsp(515,24) '${entry.value}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${entry.value}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f2.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /cart/Cart.jsp(516,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setVar("productVariant");
    // /cart/Cart.jsp(516,24) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/cart/Cart.jsp(516,24) '${cartItem.productVariant}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cartItem.productVariant}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
    if (_jspx_th_c_005fset_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f3.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /cart/Cart.jsp(517,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setVar("product");
    // /cart/Cart.jsp(517,24) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/cart/Cart.jsp(517,24) '${productVariant.productID}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${productVariant.productID}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
    if (_jspx_th_c_005fset_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
    return false;
  }
}
