/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-03-23 01:18:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.accessDenied;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class AccessDenied_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1740052119710L));
    _jspx_dependants.put("jar:file:/C:/Users/LEGION/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/2.0.0/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602848772000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Truy cập bị từ chối - Fruit Shop</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/headercss.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        .access-denied-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 50px 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .access-denied-icon {\r\n");
      out.write("            font-size: 80px;\r\n");
      out.write("            color: #ff6b6b;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .access-denied-title {\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .access-denied-message {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            line-height: 1.5;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .access-denied-actions {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .home-button, .login-button {\r\n");
      out.write("            padding: 12px 25px;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .home-button {\r\n");
      out.write("            background-color: #4CAF50;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-button {\r\n");
      out.write("            background-color: white;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            border: 2px solid #ddd;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .home-button:hover {\r\n");
      out.write("            background-color: #3e8e41;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-button:hover {\r\n");
      out.write("            background-color: #f5f5f5;\r\n");
      out.write("            border-color: #ccc;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .fruit-decoration {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            opacity: 0.1;\r\n");
      out.write("            z-index: -1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .fruit-1 {\r\n");
      out.write("            top: 10%;\r\n");
      out.write("            left: 5%;\r\n");
      out.write("            font-size: 50px;\r\n");
      out.write("            transform: rotate(-15deg);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .fruit-2 {\r\n");
      out.write("            bottom: 15%;\r\n");
      out.write("            right: 7%;\r\n");
      out.write("            font-size: 60px;\r\n");
      out.write("            transform: rotate(20deg);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .fruit-3 {\r\n");
      out.write("            top: 60%;\r\n");
      out.write("            left: 8%;\r\n");
      out.write("            font-size: 45px;\r\n");
      out.write("            transform: rotate(35deg);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .fruit-4 {\r\n");
      out.write("            top: 15%;\r\n");
      out.write("            right: 10%;\r\n");
      out.write("            font-size: 55px;\r\n");
      out.write("            transform: rotate(-25deg);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Access Denied Content -->\r\n");
      out.write("<div class=\"access-denied-container\">\r\n");
      out.write("    <!-- Decorative fruits background -->\r\n");
      out.write("    <div class=\"fruit-decoration fruit-1\"><i class=\"fa-solid fa-apple-whole\"></i></div>\r\n");
      out.write("    <div class=\"fruit-decoration fruit-2\"><i class=\"fa-solid fa-lemon\"></i></div>\r\n");
      out.write("    <div class=\"fruit-decoration fruit-3\"><i class=\"fa-solid fa-strawberry\"></i></div>\r\n");
      out.write("    <div class=\"fruit-decoration fruit-4\"><i class=\"fa-solid fa-carrot\"></i></div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"access-denied-icon\">\r\n");
      out.write("        <i class=\"fa-solid fa-lock\"></i>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <h1 class=\"access-denied-title\">Truy cập bị từ chối</h1>\r\n");
      out.write("\r\n");
      out.write("    <p class=\"access-denied-message\">\r\n");
      out.write("        Rất tiếc, bạn không có quyền truy cập vào trang này.\r\n");
      out.write("        Vui lòng đăng nhập với tài khoản có quyền truy cập phù hợp hoặc liên hệ với quản trị viên để được hỗ trợ.\r\n");
      out.write("    </p>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"access-denied-actions\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/products?action=find\" class=\"home-button\">\r\n");
      out.write("            <i class=\"fa-solid fa-home\"></i> Trang chủ\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/templates/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
